### ISSUE TITLE
Formatting Issue with US Governor CVS biography data.

### ISSUE THREAD

**Issue by ciscorucinski** [CivilServiceUSA/us-governors#1]
There are unescaped quotes in the biography data of all US Governors that have nicknames. Github's CVS renderer cannot display the US Governors data (although it can render other CVS correctly). Github gives the following warning when looking at the [CVS datasource](https://github.com/CivilServiceUSA/us-governors/blob/master/us-governors/data/us-governors.csv)

    We can make this file beautiful and searchable if this error is corrected: Missing or stray quote in line 2

After importing the data into Google Sheets, I found that this issue affects 21 lines of data. `Lines 2, 5, 6, 8, 10, 14, 18, 20, 21, 23, 26, 31, 32, 38, 39, 43, 44, 46, 47, 50, and 51.`

**Comment by AlJohri** [comment]
Another one for https://github.com/CivilServiceUSA/us-governors/blob/master/us-governors/data/us-governors.csv

```
 We can make this file beautiful and searchable if this error is corrected: Missing or stray quote in line 3 
```

<img width="1051" alt="screen shot 2018-04-26 at 9 57 36 am" src="https://user-images.githubusercontent.com/2790092/39310392-4438ddd0-4938-11e8-8067-c267330411f7.png">

**Comment by AlJohri** [comment]
I think this line is the issue: https://github.com/CivilServiceUSA/us-governors/blob/master/.scripts/convert-csv.js#L175

@manifestinteractive can you use a csv library to output the csv instead of the comma join?

**Comment by ciscorucinski** [comment]
Just to be clear, here is a snippet of the bad formatting for the file

    "William Martin "Bill" Walker (born April 16, 1951) is an American attorney and politician who is the 13th and current Governor of Alaska. He is the second native-born governor of Alaska after William A. Egan (1959–1966 and 1970–1974)."
                    ^    ^

In Google Sheets, this one cell's data will be incorrectly split across 3 cells.

**Comment by manifestinteractive** [comment]
The CSV for this file is specific to this project.  If you want the raw CSV, you can always use the source this project actually downloads from:

https://docs.google.com/spreadsheets/d/1R5YEDPBZnlKzDtq3tf8pF55Ud68EYoBhbyMhq6ymB2Q/edit#gid=539831285

100% of our date is auto generated from that file.  Closing this issue out since I can't fix it, and you can already access the data you need at the link provided.

**Comment by ciscorucinski** [comment]
@manifestinteractive this file will become the 117th next year? Are these Google Docs listed in the readme's and I'm just missing it? Doesn't seem like open data when most standard parsers will not parse it correctly. Would love to have access to all the Google Docs, too.

**Comment by manifestinteractive** [comment]
Each repo that we maintain that has a data source contains a `Data Source` section that contains a link to the CSV file.  In this case, that is in this section.

https://github.com/CivilServiceUSA/us-governors#data-source
