### ISSUE TITLE
Janet Mills (Governor ME) is incorrectly tagged as belonging to the republican party

### ISSUE THREAD

**Issue by budhiraja** [CivilServiceUSA/us-governors#13]
Here is the data row :

"Maine","maine","ME","me","36856","governor"**,"**republican**"**,"Janet Mills","janet-mills","Janet",,"Mills",,,"JA-net MILZ","female","white-american","unspecified",,"1947-12-30","2019-01-01","2022-12-31","Janet T. Mills is the Democratic Governor of Maine. Mills was elected to the office on November 6, 2018. Mills served as Maine attorney general from 2009 to 2010 and again assumed office in 2012.","207-287-3531","207-287-1034","44.3069799","-69.784334","1 State House Station, Augusta, ME 04333","1",,"State House",,,"Augusta","ME","04333","Sta","https://www.maine.gov/governor/","https://www.maine.gov/governor/mills/contact","https://www.facebook.com/millsforgovernor/","JanetMillsforME","https://twitter.com/JanetMillsforME","https://cdn.civil.services/us-governors/headshots/512x512/janet-mills.jpg"

**Comment by manifestinteractive** [comment]
@budhiraja any chance you can provide what the correct info should be? A link to where we can verify this info would also be helpful.

**Comment by budhiraja** [comment]
@manifestinteractive : Her wikipedia entry says she is a democrat: https://en.wikipedia.org/wiki/Janet_Mills.
The data row also says she is the "Democratic Governor of Maine".

**Comment by budhiraja** [comment]
@manifestinteractive can this be updated in the data and the bug be closed?

**Comment by manifestinteractive** [comment]
This will be going out in the next release.
