### ISSUE TITLE
updated governor twitter urls in google sheets file

### ISSUE THREAD

**Issue by gmmurray** [CivilServiceUSA/us-governors#14]
changed the urls for the following states:

- Alabama
- Oklahoma
- South Carolina
- Texas
- Utah
- Florida
Noticed the Kentucky governor is out of date so I did not change that twitter handle since the whole profile needs to be updated.

**Comment by manifestinteractive** [comment]
Going out with the next API deployment.  Apologies for the delays, life's been kind of crazy for everyone.
