### ISSUE TITLE
include term lengths and term limits?

### ISSUE THREAD

**Issue by AlJohri** [CivilServiceUSA/us-governors#2]
hi @manifestinteractive, I was wondering if its possible to include term length and term limits for each state in the data?

I want to know which governors are hitting their term limits and when.

Looks like this information can be found here: https://ballotpedia.org/States_with_gubernatorial_term_limits

**Comment by manifestinteractive** [comment]
This is not really something I plan on including in this project.   You may be able to use the existing `term_end` column, as this will tell you when their current term ends.
