### ISSUE TITLE
Issues with addresses/GPS coordindates

### ISSUE THREAD

**Issue by wandering-andy** [CivilServiceUSA/us-governors#20]
1. John Edwards (LA) - His address shows up in AZ. Address should be: Louisiana State Capitol, Baton Rouge, LA
2. Mark Gordon (WY) - GPS coordinates are in Canada. More accurate address: 200 W 24th St, Cheyenne, WY 82001. More accurate coordinates: 41.1402682, -104.8202289
3. Eric Holcombe (IN) - GPS coordinates are almost identical to those for IL. More accurate address: 200 W. Washington St., Second Floor, Rm. 206, Indianapolis, IN 46204. More accurate coordinates 39.76716995239258, -86.16262817382812

Edit:
4. Mike Dunleavy (AK) - Physical address: 120 4th St, Juneau, AK 99801. GPS Coordinates: 58.301677, -134.410995

**Comment by manifestinteractive** [comment]
@wandering-andy thanks for this, I will be going through this list for our next API release here this weekend and making sure the US Governor Data is current and correct.

**Comment by manifestinteractive** [comment]
This is fixed with v1.4.0 release.
