### ISSUE TITLE
end of term date is wrong

### ISSUE THREAD

**Issue by AlJohri** [CivilServiceUSA/us-governors#5]
almost all governors are listed as jan 1, 2019 but it differs a bit state to state. This table has all the years: https://en.wikipedia.org/wiki/List_of_current_United_States_governors#State_governors

>The current term ends in January of the given year for every state except for Alaska, Hawaii, North Dakota, and Kentucky, where the term ends in December of that year's election.

**Comment by manifestinteractive** [comment]
This will be fixed in the next release.
