### ISSUE TITLE
Update Governors for 2019

### ISSUE THREAD

**Issue by nickoneill** [CivilServiceUSA/us-governors#6]
Working on this in the doc now

**Comment by nickoneill** [comment]
Data is fully up-to-date in the doc @manifestinteractive

**Comment by nickoneill** [comment]
Needs image data to accompany #8

**Comment by dmaynard** [comment]
Georgia Governor is Brian Kemp, not Nathan Deal

**Comment by dmaynard** [comment]
Kentucky Governor is Any Beshear democrat NOT Mathew Bevin republican

**Comment by manifestinteractive** [comment]
These updates will be pushed out in the next release.
